#!/bin/bash
# Create minimal valid PNG icons using base64 encoded data

# 16x16 blue icon with white key shape
echo "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAARUlEQVQ4je2SMQoAIQwE3f//9NpYWFhYWAhBEAQREREZmW2EBEREBBER2ZlZQEREREREZGZmZmZmZmYiIiIiIiKDAwAA//8DAFtvC3naJY4LAAAAAElFTkSuQmCC" | base64 -d > icon16.png

# 48x48 blue icon
echo "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QA/wD/AP+gvaeTAAAASUlEQVRoge3OMQ0AAAwDoKmn/zINAzAMwzAMwzAMwzAMwzAMwzAMwzAMwzAMwzAMwzAMwzAMwzAMwzAMwzAMwzAMwzAMwzAMwwAA//8DAL5vA1yzEEKiAAAAAElFTkSuQmCC" | base64 -d > icon48.png

# 128x128 blue icon
echo "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAASUlEQVR4nO3BMQ0AAAwCoNm/9C5IUwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwGAAD//wMAJp4AASVEfmEAAAAASUVORK5CYII=" | base64 -d > icon128.png

echo "Placeholder icons created"
